// généré automatiquement depuis temples.xlsx - fr180
const staticTemples = [
  { id: 1, x: 496, y: 514, name: 'Mytilene', type: '10% chass', bonus: 'Augmente le bonus de concentration de la chasseresse de 10% supplementaires', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 2, x: 523, y: 474, name: 'Kaiete', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 3, x: 463, y: 476, name: 'Pylos', type: '6% hydres', bonus: 'Augmente les valeurs offensive et defensive de Hydres de 6%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 4, x: 464, y: 524, name: 'Olbia', type: '6% cout ter', bonus: 'Reduit tous les couts de recrutement d\'unites terrestres de 6%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 5, x: 525, y: 559, name: 'Khrisafa', type: '10% cout nav', bonus: 'Reduire tous les couts de recrutement d\'unites navales de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 6, x: 497, y: 551, name: 'Olynthus', type: '3% force hero', bonus: 'Force heroique augmente l\'attaque de toutes les unites de 3%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 7, x: 504, y: 438, name: 'Megare', type: '5% nav', bonus: 'Augmente la valeur offensive de toutes les unites navales de 5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 8, x: 472, y: 544, name: 'Lissus', type: '6% centaures', bonus: 'Augmente les valeurs offensive et defensive de Centaures de 6%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 9, x: 543, y: 477, name: 'Tripoli', type: '10% ressources', bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 10, x: 422, y: 529, name: 'Metapontum', type: '8% Erinyes', bonus: 'Augmente la puissance offensive de Erinyes de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 11, x: 437, y: 547, name: 'Apamea', type: '10% cava', bonus: 'Augmente la puissance offensive de Cavaliers de 10%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 12, x: 465, y: 428, name: 'Pergamum', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 13, x: 542, y: 575, name: 'Cebrene', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 14, x: 425, y: 474, name: 'Crotone', type: '10% cout nav', bonus: 'Reduire tous les couts de recrutement d\'unites navales de 10%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 15, x: 440, y: 447, name: 'Myrmekion', type: '8% Erinyes', bonus: 'Augmente la puissance offensive de Erinyes de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 16, x: 581, y: 540, name: 'Akrillai', type: '6% cout nav', bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 17, x: 481, y: 397, name: 'Tragana', type: '8% hop', bonus: 'Augmente les valeurs offensive et defensive de Hoplites de 8%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 18, x: 434, y: 412, name: 'Tanagra', type: '3% all', bonus: 'Augmente la valeur offensive de toutes les unites de 3%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 19, x: 585, y: 573, name: 'Himere', type: '10% festi', bonus: 'Avec le Festival Caritatif, le cout de la Marche Triomphale est encore reduit de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 20, x: 518, y: 393, name: 'Kallipolis', type: '10% sacrifice', bonus: 'La generation de fureur avec le sacrifice d\'Ares est augmentee de 15%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 21, x: 607, y: 494, name: 'Borysthenes', type: '10% cout nav', bonus: 'Reduire tous les couts de recrutement d\'unites navales de 10%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 22, x: 406, y: 513, name: 'Malia', type: '8% trieres', bonus: 'Augmente la puissance offensive de Trieres de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 23, x: 513, y: 597, name: 'Kepoi', type: '4.5% duree ter', bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 24, x: 598, y: 457, name: 'Orestias', type: '10% cout nav', bonus: 'Reduire tous les couts de recrutement d\'unites navales de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 25, x: 403, y: 490, name: 'Cnide', type: '8% cont', bonus: 'Augmente toutes les valeurs offensives des armes Contondant de 8%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 26, x: 406, y: 414, name: 'Clazomenae', type: '8% bf', bonus: 'Augmente la puissance offensive de Bateaux-feux de 8%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 27, x: 552, y: 379, name: 'Siteia', type: '8% bf', bonus: 'Augmente la puissance offensive de Bateaux-feux de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 28, x: 406, y: 585, name: 'Mycenes', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 29, x: 424, y: 605, name: 'Cleonae', type: '8% spartes', bonus: 'Augmente la puissance offensive de Spartes de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 30, x: 528, y: 629, name: 'Thapsos', type: '5% nav', bonus: 'Augmente la valeur offensive de toutes les unites navales de 5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 31, x: 604, y: 557, name: 'Mochlos', type: '2% all', bonus: 'Augmente la valeur defensive de toutes les unites de 2%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 32, x: 587, y: 604, name: 'Halieis', type: '10% frondeurs', bonus: 'Augmente la puissance offensive de Frondeurs de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 33, x: 626, y: 529, name: 'Edessa', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 34, x: 399, y: 566, name: 'Amnisos', type: '10% festi', bonus: 'Avec le Festival Caritatif, le cout de la Marche Triomphale est encore reduit de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 35, x: 372, y: 516, name: 'Stratos', type: '8% Erinyes', bonus: 'Augmente la puissance offensive de Erinyes de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 36, x: 536, y: 608, name: 'Psychro', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 37, x: 523, y: 349, name: 'Semasus', type: '120 Mariage', bonus: 'Mariage donne 120 ressources en plus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 38, x: 476, y: 654, name: 'Chorsiae', type: '2% all', bonus: 'Augmente la valeur defensive de toutes les unites de 2%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 39, x: 346, y: 484, name: 'Corcyra', type: '10% cout ter', bonus: 'Reduit tous les couts de recrutement d\'unites terrestres de 10%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 40, x: 506, y: 644, name: 'Delphes', type: '15% hop', bonus: 'Augmente la valeur defensive des Hoplites de 15%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 41, x: 590, y: 629, name: 'Lampsaque', type: '#N/A', bonus: 'Augmente la puissance offensive de Manticores de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 42, x: 642, y: 450, name: 'Thassos', type: '10% frondeurs', bonus: 'Augmente la puissance offensive de Frondeurs de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 43, x: 627, y: 584, name: 'Heraclea', type: '10% chars', bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 44, x: 385, y: 423, name: 'Emporion', type: '8% meduses', bonus: 'Augmente la puissance offensive de Meduses de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 45, x: 615, y: 420, name: 'Massalia', type: '10% chars', bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 46, x: 371, y: 441, name: 'Cnidus', type: '8% cont', bonus: 'Augmente toutes les valeurs offensives des armes Contondant de 8%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 47, x: 647, y: 487, name: 'Athmonia', type: '5% nav', bonus: 'Augmente la valeur offensive de toutes les unites navales de 5%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 48, x: 570, y: 621, name: 'Miletos', type: '10% cava', bonus: 'Augmente la puissance offensive de Cavaliers de 10%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 49, x: 610, y: 604, name: 'Kastoria', type: '10% chars', bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 50, x: 350, y: 462, name: 'Lykosoura', type: '4.5% duree ter', bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 51, x: 405, y: 638, name: 'Tirynthe', type: '8% bibi', bonus: 'Augmente la valeur defensive des Biremes de 8%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 52, x: 346, y: 567, name: 'Tylissos', type: '20% ressources', bonus: 'Augmente la production de bois, de pierre et d\'argent de 20%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 53, x: 555, y: 328, name: 'Patras', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 54, x: 327, y: 462, name: 'Karphi', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 55, x: 666, y: 427, name: 'Astacus', type: '8% bf', bonus: 'Augmente la puissance offensive de Bateaux-feux de 8%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 56, x: 541, y: 668, name: 'Pharos', type: '10% cerberes', bonus: 'Augmente la valeur defensive des Cerberes de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 57, x: 616, y: 629, name: 'Ankon', type: '8% blanche', bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 58, x: 492, y: 680, name: 'Platees', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 59, x: 335, y: 531, name: 'Abdere', type: '8% cont', bonus: 'Augmente toutes les valeurs offensives des armes Contondant de 8%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 60, x: 475, y: 333, name: 'Kardamyli', type: '3% all', bonus: 'Augmente la valeur offensive de toutes les unites de 3%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 61, x: 680, y: 495, name: 'Iasos', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 62, x: 659, y: 467, name: 'Calydon', type: '8% bf', bonus: 'Augmente la puissance offensive de Bateaux-feux de 8%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 63, x: 439, y: 652, name: 'Aegium', type: '6% cout ter', bonus: 'Reduit tous les couts de recrutement d\'unites terrestres de 6%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 64, x: 365, y: 395, name: 'Silivri', type: '3% all', bonus: 'Augmente la valeur offensive de toutes les unites de 3%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 65, x: 381, y: 375, name: 'Sidon', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 66, x: 641, y: 612, name: 'Hermonassa', type: '10% chass', bonus: 'Augmente le bonus de concentration de la chasseresse de 10% supplementaires', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 67, x: 463, y: 689, name: 'Sozopolis', type: '5% mythiques', bonus: 'Augmente la puissance offensive de toutes les unites Mythique de 5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 68, x: 697, y: 447, name: 'Phanagoria', type: '3% all', bonus: 'Augmente la valeur offensive de toutes les unites de 3%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 69, x: 360, y: 642, name: 'Eleusis', type: '10% ressources', bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 70, x: 687, y: 521, name: 'Kamarina', type: '8% bf', bonus: 'Augmente la puissance offensive de Bateaux-feux de 8%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 71, x: 404, y: 341, name: 'Oreus', type: '10% ressources', bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 72, x: 402, y: 675, name: 'Imbros', type: '10% cerberes', bonus: 'Augmente la valeur defensive des Cerberes de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 73, x: 611, y: 356, name: 'Perga', type: '15% adm', bonus: 'Augmente l\'effet de l\'appel de la mer de 15%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 74, x: 659, y: 398, name: 'Akrai', type: '8% bf', bonus: 'Augmente la puissance offensive de Bateaux-feux de 8%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 75, x: 323, y: 401, name: 'Heliopolis', type: '2% all', bonus: 'Augmente la valeur defensive de toutes les unites de 2%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 76, x: 311, y: 515, name: 'Zakros', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 77, x: 431, y: 330, name: 'Kios', type: '6% cout ter', bonus: 'Reduit tous les couts de recrutement d\'unites terrestres de 6%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 78, x: 385, y: 648, name: 'Abydos', type: '120 Mariage', bonus: 'Mariage donne 120 ressources en plus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 79, x: 633, y: 654, name: 'Oricos', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 80, x: 591, y: 343, name: 'Lessa', type: '4.5% duree ter', bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 81, x: 311, y: 442, name: 'Soli', type: '10% frondeurs', bonus: 'Augmente la puissance offensive de Frondeurs de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 82, x: 491, y: 700, name: 'Histria', type: '6% cout nav', bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 83, x: 467, y: 308, name: 'Pagases', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 84, x: 306, y: 540, name: 'Demetrias', type: '8% spartes', bonus: 'Augmente la puissance offensive de Spartes de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 85, x: 314, y: 619, name: 'Pharnacia', type: '8% bf', bonus: 'Augmente la puissance offensive de Bateaux-feux de 8%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 86, x: 287, y: 519, name: 'Parthenope', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 87, x: 704, y: 598, name: 'Dascylion', type: '4.5% duree ter', bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 88, x: 676, y: 633, name: 'Tithoraea', type: '4.5% duree ter', bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 89, x: 622, y: 313, name: 'Copae', type: '4.5% duree nav', bonus: 'Reduire toutes les durees de recrutement d\'unites navales de 4.5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 90, x: 276, y: 491, name: 'Juktas', type: '8% cont', bonus: 'Augmente toutes les valeurs offensives des armes Contondant de 8%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 91, x: 714, y: 567, name: 'Cynossema', type: '3% force hero', bonus: 'Force heroique augmente l\'attaque de toutes les unites de 3%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 92, x: 326, y: 371, name: 'Kimmerikon', type: '10% cout ter', bonus: 'Reduit tous les couts de recrutement d\'unites terrestres de 10%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 93, x: 451, y: 288, name: 'Alexandreia', type: '#N/A', bonus: 'Augmente la puissance offensive de Manticores de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 94, x: 297, y: 406, name: 'Myre', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 95, x: 501, y: 290, name: 'Tegee', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 96, x: 384, y: 312, name: 'Petsofa', type: '8% sirenes', bonus: 'Augmente la puissance offensive de Sirenes de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 97, x: 634, y: 337, name: 'Hemeroskopeion', type: '10% ressources', bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 98, x: 451, y: 711, name: 'Delos', type: '6% hydres', bonus: 'Augmente les valeurs offensive et defensive de Hydres de 6%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 99, x: 334, y: 646, name: 'Scione', type: '10% ressources', bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 100, x: 597, y: 311, name: 'Hermione', type: '6% cout nav', bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 101, x: 418, y: 705, name: 'Mulai', type: '10% sacrifice', bonus: 'La generation de fureur avec le sacrifice d\'Ares est augmentee de 15%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 102, x: 656, y: 363, name: 'Nagidos', type: '3% all', bonus: 'Augmente la valeur offensive de toutes les unites de 3%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 103, x: 589, y: 292, name: 'Boura', type: '10% chass', bonus: 'Augmente le bonus de concentration de la chasseresse de 10% supplementaires', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 104, x: 714, y: 509, name: 'Alexandretta', type: '6% non-um', bonus: 'Augmente la valeur offensive de toutes les unites terrestres non mythiques de 6%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 105, x: 712, y: 408, name: 'Thyria', type: '2% all', bonus: 'Augmente la valeur defensive de toutes les unites de 2%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 106, x: 283, y: 601, name: 'Haliarte', type: '10% cerberes', bonus: 'Augmente la valeur defensive des Cerberes de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 107, x: 415, y: 278, name: 'Lamia', type: '8% trieres', bonus: 'Augmente la puissance offensive de Trieres de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 108, x: 378, y: 717, name: 'Bouthroton', type: '8% blanche', bonus: 'Augmente toutes les valeurs offensives des armes Blanche de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 109, x: 271, y: 460, name: 'Ephyra', type: '8% griffons', bonus: 'Augmente la puissance offensive de Griffons de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 110, x: 450, y: 267, name: 'Seeres', type: '2% all', bonus: 'Augmente la valeur defensive de toutes les unites de 2%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 111, x: 282, y: 569, name: 'Olous', type: '8% arme de jet', bonus: 'Augmente toutes les valeurs offensives des armes De jet de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 112, x: 476, y: 726, name: 'Vrokastro', type: '6% cout nav', bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 113, x: 711, y: 378, name: 'Corinthe', type: '10% cava', bonus: 'Augmente la puissance offensive de Cavaliers de 10%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 114, x: 736, y: 520, name: 'Nauplios', type: '10% chars', bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 115, x: 369, y: 697, name: 'Assus', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 116, x: 663, y: 322, name: 'Leontinoi', type: '10% ressources', bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 117, x: 261, y: 541, name: 'Menelaion', type: '10% chars', bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 118, x: 335, y: 330, name: 'Karyes', type: '3% force hero', bonus: 'Force heroique augmente l\'attaque de toutes les unites de 3%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 119, x: 604, y: 721, name: 'Athenes', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 120, x: 357, y: 321, name: 'Tauromenion', type: '6% hydres', bonus: 'Augmente les valeurs offensive et defensive de Hydres de 6%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 121, x: 579, y: 267, name: 'Magnesia', type: '5% mythiques', bonus: 'Augmente la puissance offensive de toutes les unites Mythique de 5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 122, x: 458, y: 738, name: 'Alalcomenae', type: '10% chars', bonus: 'Augmente les valeurs offensive et defensive de Chars de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 123, x: 541, y: 277, name: 'Parthenopolis', type: '10% ressources', bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 124, x: 575, y: 717, name: 'Nichoria', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 125, x: 667, y: 346, name: 'Gythio', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 126, x: 670, y: 680, name: 'Naucratis', type: '10% cout nav', bonus: 'Reduire tous les couts de recrutement d\'unites navales de 10%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 127, x: 656, y: 719, name: 'Stagire', type: '2% all', bonus: 'Augmente la valeur defensive de toutes les unites de 2%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 128, x: 263, y: 627, name: 'Acanthus', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 129, x: 273, y: 391, name: 'Helike', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 130, x: 340, y: 716, name: 'Sicyon', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 131, x: 560, y: 743, name: 'Peiraieus', type: '6% cout ter', bonus: 'Reduit tous les couts de recrutement d\'unites terrestres de 6%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 132, x: 466, y: 239, name: 'Camiros', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 133, x: 239, y: 512, name: 'Actium', type: '10% ressources', bonus: 'Augmente la production de bois, de pierre et d\'argent de 10%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 134, x: 763, y: 502, name: 'Heraklion', type: '8% arme de jet', bonus: 'Augmente toutes les valeurs offensives des armes De jet de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 135, x: 504, y: 759, name: 'Sybaris', type: '4.5% duree ter', bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 136, x: 616, y: 255, name: 'Rhithymna', type: '6% cout nav', bonus: 'Reduire tous les couts de recrutement d\'unites navales de 6%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 137, x: 694, y: 314, name: 'Nemea', type: '4.5% duree nav', bonus: 'Reduire toutes les durees de recrutement d\'unites navales de 4.5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 138, x: 761, y: 535, name: 'Phaistos', type: '6% non-um', bonus: 'Augmente la valeur offensive de toutes les unites terrestres non mythiques de 6%', size: 'small', owner: 0, contest: 'none', focus: true },
  { id: 139, x: 435, y: 751, name: 'Laodicea', type: '4.5% duree ter', bonus: 'Reduit toutes les durees de recrutement d\'unites terrestres de 4.5%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 140, x: 690, y: 336, name: 'Idalium', type: '2% all', bonus: 'Augmente la valeur defensive de toutes les unites de 2%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 141, x: 281, y: 352, name: 'Poseidonia', type: '6% non-um', bonus: 'Augmente la valeur offensive de toutes les unites terrestres non mythiques de 6%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 142, x: 734, y: 613, name: 'Byzance', type: 'PROD T', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 143, x: 384, y: 259, name: 'Thurii', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 144, x: 744, y: 563, name: 'Kydonia', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 145, x: 609, y: 275, name: 'Koukounaries', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 146, x: 760, y: 457, name: 'Chamaizi', type: '3% all', bonus: 'Augmente la valeur offensive de toutes les unites de 3%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 147, x: 570, y: 242, name: 'Le Piree', type: '3% all', bonus: 'Augmente la valeur offensive de toutes les unites de 3%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 148, x: 466, y: 767, name: 'Tenedos', type: 'Portail', bonus: 'Portail vers Olympus', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 149, x: 365, y: 278, name: 'Argyroupoli', type: '#N/A', bonus: 'Augmente la puissance offensive de Manticores de 8%', size: 'small', owner: 0, contest: 'none', focus: false },
  { id: 150, x: 313, y: 311, name: 'Lekhaion', type: '6% cout ter', bonus: 'Reduit tous les couts de recrutement d\'unites terrestres de 6%', size: 'small', owner: 0, contest: 'none', focus: true },
];
 
module.exports = { staticTemples };